apiVersion: apps/v1  #bucket
kind: Deployment
metadata:
   name: posts-depl  #depl to show deployment
spec:
   replicas: 1       #no of pods to create
   selector:         # find  all pods with label posts
      matchLabels:
         app: posts
   template:         # the pod config. We need the pod to givr label posts
      metadata:
         labels:
            app: posts
      spec:
         containers:
            - name: posts
              image: mistryakshar54/posts

---
apiVersion: v1
kind: Service
metadata:
   name: posts-cluserip-srv
spec:
   selector:
      app: posts
   ports:
      - name: posts
        protocol: TCP
        port: 8000
        targetPort: 8000