apiVersion: apps/v1  #bucket
kind: Deployment
metadata:
   name: posts-client-depl  #depl to show deployment
spec:
   replicas: 1       #no of pods to create
   selector:         # find  all pods with label posts-client
      matchLabels:
         app: posts-client
   template:         # the pod config. We need the pod to givr label posts-client
      metadata:
         labels:
            app: posts-client
      spec:
         containers:
            - name: posts-client
              image: mistryakshar54/posts-client

---
apiVersion: v1
kind: Service
metadata:
   name: posts-client-cluserip-srv
spec:
   selector:
      app: posts-client
   ports:
      - name: posts-client
        protocol: TCP
        port: 3000
        targetPort: 3000