apiVersion: apps/v1
kind: Deployment
metadata:
    name: auth-depl
spec:
    replicas: 1
    selector:
        matchLabels:
            app: auth
    template:
        metadata:
            labels:
                app: auth
        spec:
            containers:
                - name: auth
                  image: mistryakshar54/ticketing-auth
                  env:
                    - name: JWT_KEY    #Available to container as JWT_KEY=YOUR_STORED_KEY
                      valueFrom:
                        secretKeyRef:
                            name: jwt-secret   # { jwt-secret : { JWT_KEY : YOUR_STORED_KEY } }
                            key: JWT_KEY
                    - name: MONGO_URL    #Available to container as MONGO_URL
                      value: 'mongodb://tickets-mongo-srv:27017/users'

---
apiVersion: v1
kind: Service
metadata:
    name: auth-srv 
spec:
    selector:
        app: auth
    ports:
        - name: auth
          protocol: TCP
          port: 3000   
          targetPort: 3000   
