apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata : 
    name: ingress-srv
    annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
    rules:
        - host: ticketing.dev
          http: 
            paths:
                - path: /api/users/?(.*)
                  backend:
                    serviceName: auth-srv
                    servicePort: 3000
                - path: /?(.*)
                  backend:
                    serviceName: ticketing-client-srv
                    servicePort: 3000
                # - path: /api/posts
                #   backend:
                #     serviceName: query-service-srv
                #     servicePort: 8002
                # - path: /api/posts/?(.*)/comments
                #   backend:
                #     serviceName: comments-srv
                #     servicePort: 8001
                # - path: /?(.*)
                #   backend:
                #     serviceName: posts-client-cluserip-srv
                #     servicePort: 3000
