apiVersion: apps/v1
kind: Deployment
metadata:
    name: tickets-depl
spec:
    replicas: 1
    selector:
        matchLabels:
            app: tickets
    template:
        metadata:
            labels:
                app: tickets
        spec:
            containers:
                - name: tickets
                  image: mistryakshar54/ticketing-tickets
                  env:
                    - name: MONGO_URL    #Available to container as MONGO_URL
                      value: 'mongodb://tickets-mongo-srv:27017/tickets'
                    - name: JWT_KEY    #Available to container as JWT_KEY=YOUR_STORED_KEY
                      valueFrom:
                        secretKeyRef:
                            name: jwt-secret   # { jwt-secret : { JWT_KEY : YOUR_STORED_KEY } }
                            key: JWT_KEY


---
apiVersion: v1
kind: Service
metadata:
    name: tickets-srv 
spec:
    selector:
        app: tickets
    ports:
        - name: tickets
          protocol: TCP
          port: 3000   
          targetPort: 3000   
